common: &common
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: utf-8
  username: <%= Rails.application.config.app.postgres.user %>
  password: <%= Rails.application.config.app.postgres.password %>
  database: <%= Rails.application.config.app.postgres.database %>
  host: <%= Rails.application.config.app.postgres.host %>

development:
  <<: *common

test:
  <<: *common

production:
  <<: *common
