name: CI/CD
on: pull_request

jobs:
  Tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports: ['5432:5432']
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: SmA2020!
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.6
      - name: Build and run tests
        env:
          DATABASE_URL: postgres://user:@localhost:5432/stock_management_api_test
          POSTGRES_DB: stock_management_api_test
          POSTGRES_PORT: 5432
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rails db:prepare
          bundle exec rspec